// RegisterApplicationCommands.hpp - Registers the slash commands of this bot.
// May 27, 2021
// Chris M.
// https://github.com/RealTimeChris

#pragma once

#include "./../HelperFunctions.hpp"

namespace DiscordCoreAPI {

	class RegisterApplicationCommands {
	  public:
		RegisterApplicationCommands() {
			createStreamAudioData.dmPermission			   = false;
			createStreamAudioData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createStreamAudioData.type					   = ApplicationCommandType::Chat_Input;
			createStreamAudioData.name					   = "streamaudio";
			createStreamAudioData.description			   = "Connects to a voice channel to stream audio.";
			ApplicationCommandOptionData streamAudioOptionOne{};
			streamAudioOptionOne.type		 = ApplicationCommandOptionType::String;
			streamAudioOptionOne.description = "Which ip to connect to.";
			streamAudioOptionOne.name		 = "connectionip";
			streamAudioOptionOne.required	 = true;
			createStreamAudioData.options.emplace_back(streamAudioOptionOne);
			ApplicationCommandOptionData streamAudioOptionTwo{};
			streamAudioOptionTwo.type		 = ApplicationCommandOptionType::Boolean;
			streamAudioOptionTwo.description = "Whether or not to enable retransmission of other bot's audio.";
			streamAudioOptionTwo.name		 = "botaudio";
			streamAudioOptionTwo.required	 = true;
			createStreamAudioData.options.emplace_back(streamAudioOptionTwo);

			createDisconnectData.dmPermission			  = false;
			createDisconnectData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createDisconnectData.type					  = ApplicationCommandType::Chat_Input;
			createDisconnectData.name					  = "disconnect";
			createDisconnectData.description			  = "Disconnect from the current voice channel.";

			reactionRoleData.dmPermission			  = false;
			reactionRoleData.defaultMemberPermissions = Permission::Use_Application_Commands;
			reactionRoleData.description			  = "Setup or instantiate the 'reaction role' menu.";
			reactionRoleData.name					  = "reactionrole";
			reactionRoleData.type					  = ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData reactionRoleDataOptionOh;
			reactionRoleDataOptionOh.type		 = ApplicationCommandOptionType::Sub_Command;
			reactionRoleDataOptionOh.name		 = "add";
			reactionRoleDataOptionOh.description = "Adds a role to the current list of roles.";
			ApplicationCommandOptionData reactionRoleDataOptionOneOne;
			reactionRoleDataOptionOneOne.type		 = ApplicationCommandOptionType::RoleData;
			reactionRoleDataOptionOneOne.description = "Which role to add.";
			reactionRoleDataOptionOneOne.name		 = "role";
			reactionRoleDataOptionOneOne.required	 = true;
			reactionRoleDataOptionOh.options.emplace_back(reactionRoleDataOptionOneOne);
			reactionRoleData.options.emplace_back(reactionRoleDataOptionOh);
			ApplicationCommandOptionData reactionRoleDataOptionTwo;
			reactionRoleDataOptionTwo.type		  = ApplicationCommandOptionType::Sub_Command;
			reactionRoleDataOptionTwo.name		  = "remove";
			reactionRoleDataOptionTwo.description = "Removes a role from the current list of roles.";
			ApplicationCommandOptionData reactionRoleDataOptionTwoOne;
			reactionRoleDataOptionTwoOne.type		 = ApplicationCommandOptionType::RoleData;
			reactionRoleDataOptionTwoOne.description = "Which role to remove.";
			reactionRoleDataOptionTwoOne.name		 = "role";
			reactionRoleDataOptionTwoOne.required	 = true;
			reactionRoleDataOptionTwo.options.emplace_back(reactionRoleDataOptionTwoOne);
			reactionRoleData.options.emplace_back(reactionRoleDataOptionTwo);
			ApplicationCommandOptionData reactionRoleDataOptionThree;
			reactionRoleDataOptionThree.type		= ApplicationCommandOptionType::Sub_Command;
			reactionRoleDataOptionThree.name		= "instantiate";
			reactionRoleDataOptionThree.description = "Posts the 'react-to-be-roled' message in the current channel along with a provided message.";
			ApplicationCommandOptionData reactionRoleDataOptionThreeOne;
			reactionRoleDataOptionThreeOne.type		   = ApplicationCommandOptionType::String;
			reactionRoleDataOptionThreeOne.description = "Which message to provide on the 'React-to-be-roled' menu.";
			reactionRoleDataOptionThreeOne.name		   = "message";
			reactionRoleDataOptionThreeOne.required	   = true;
			reactionRoleDataOptionThree.options.emplace_back(reactionRoleDataOptionThreeOne);
			reactionRoleData.options.emplace_back(reactionRoleDataOptionThree);

			createSetDefaultRoleIdsData.dmPermission			 = false;
			createSetDefaultRoleIdsData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createSetDefaultRoleIdsData.description				 = "Sets a default role to be added to a new user, or removes one.";
			createSetDefaultRoleIdsData.name					 = "setdefaultrole";
			createSetDefaultRoleIdsData.type					 = ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createSetDefaultRoleIdsDataOptionOh;
			createSetDefaultRoleIdsDataOptionOh.type		= ApplicationCommandOptionType::Sub_Command;
			createSetDefaultRoleIdsDataOptionOh.name		= "view";
			createSetDefaultRoleIdsDataOptionOh.description = "View the list of default roles.";
			createSetDefaultRoleIdsData.options.emplace_back(createSetDefaultRoleIdsDataOptionOh);
			ApplicationCommandOptionData createSetDefaultRoleIdsDataOptionOne;
			createSetDefaultRoleIdsDataOptionOne.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetDefaultRoleIdsDataOptionOne.name		 = "add";
			createSetDefaultRoleIdsDataOptionOne.description = "Add a new default role to the list.";
			ApplicationCommandOptionData createSetDefaultRoleIdsDataOptionOneTwo;
			createSetDefaultRoleIdsDataOptionOneTwo.type		= ApplicationCommandOptionType::RoleData;
			createSetDefaultRoleIdsDataOptionOneTwo.description = "Which role to add.";
			createSetDefaultRoleIdsDataOptionOneTwo.name		= "role";
			createSetDefaultRoleIdsDataOptionOneTwo.required	= true;
			createSetDefaultRoleIdsDataOptionOne.options.emplace_back(createSetDefaultRoleIdsDataOptionOneTwo);
			createSetDefaultRoleIdsData.options.emplace_back(createSetDefaultRoleIdsDataOptionOne);
			ApplicationCommandOptionData createSetDefaultRoleIdsDataOptionTwo;
			createSetDefaultRoleIdsDataOptionTwo.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetDefaultRoleIdsDataOptionTwo.name		 = "remove";
			createSetDefaultRoleIdsDataOptionTwo.description = "remove a default role from the list.";
			ApplicationCommandOptionData createSetDefaultRoleIdsDataOptionTwoTwo;
			createSetDefaultRoleIdsDataOptionTwoTwo.type		= ApplicationCommandOptionType::RoleData;
			createSetDefaultRoleIdsDataOptionTwoTwo.description = "Which role to remove.";
			createSetDefaultRoleIdsDataOptionTwoTwo.name		= "role";
			createSetDefaultRoleIdsDataOptionTwoTwo.required	= true;
			createSetDefaultRoleIdsDataOptionTwo.options.emplace_back(createSetDefaultRoleIdsDataOptionTwoTwo);
			createSetDefaultRoleIdsData.options.emplace_back(createSetDefaultRoleIdsDataOptionTwo);

			createBotInfoCommandData.dmPermission			  = true;
			createBotInfoCommandData.description			  = "Displays info about the current bot.";
			createBotInfoCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createBotInfoCommandData.name					  = "botinfo";
			createBotInfoCommandData.type					  = ApplicationCommandType::Chat_Input;

			createDisplayGuildsDataCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createDisplayGuildsDataCommandData.dmPermission				= true;
			createDisplayGuildsDataCommandData.description				= "View the list of servers that this bot is in.";
			createDisplayGuildsDataCommandData.name						= "displayguildsdata";
			createDisplayGuildsDataCommandData.type						= ApplicationCommandType::Chat_Input;

			createGhostCommandData.dmPermission				= false;
			createGhostCommandData.description				= "Mutes/silences a server-member.";
			createGhostCommandData.name						= "ghost";
			createGhostCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createGhostCommandData.type						= ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createGhostOptionOne;
			createGhostOptionOne.type		 = ApplicationCommandOptionType::Sub_Command;
			createGhostOptionOne.name		 = "view";
			createGhostOptionOne.description = "View the currently ghosted members.";
			createGhostCommandData.options.emplace_back(createGhostOptionOne);
			ApplicationCommandOptionData createGhostOptionTwo;
			createGhostOptionTwo.type		 = ApplicationCommandOptionType::Sub_Command;
			createGhostOptionTwo.name		 = "add";
			createGhostOptionTwo.description = "Ghosts a new server member.";
			ApplicationCommandOptionData createGhostOptionTwoTwo;
			createGhostOptionTwoTwo.name		= "user";
			createGhostOptionTwoTwo.description = "Chooses which member to ghost.";
			createGhostOptionTwoTwo.required	= true;
			createGhostOptionTwoTwo.type		= ApplicationCommandOptionType::UserData;
			createGhostOptionTwo.options.emplace_back(createGhostOptionTwoTwo);
			ApplicationCommandOptionData createGhostOptionTwoThree;
			createGhostOptionTwoThree.name		  = "reason";
			createGhostOptionTwoThree.description = "Specify a reason for the ghosting.";
			createGhostOptionTwoThree.required	  = true;
			createGhostOptionTwoThree.type		  = ApplicationCommandOptionType::String;
			createGhostOptionTwo.options.emplace_back(createGhostOptionTwoThree);
			createGhostCommandData.options.emplace_back(createGhostOptionTwo);
			ApplicationCommandOptionData createGhostOptionThree;
			createGhostOptionThree.type		   = ApplicationCommandOptionType::Sub_Command;
			createGhostOptionThree.name		   = "remove";
			createGhostOptionThree.description = "Un-Ghosts a server member.";
			ApplicationCommandOptionData createGhostOptionThreeTwo;
			createGhostOptionThreeTwo.name		  = "user";
			createGhostOptionThreeTwo.description = "Chooses which member to un-ghost.";
			createGhostOptionThreeTwo.required	  = true;
			createGhostOptionThreeTwo.type		  = ApplicationCommandOptionType::UserData;
			createGhostOptionThree.options.emplace_back(createGhostOptionThreeTwo);
			createGhostCommandData.options.emplace_back(createGhostOptionThree);

			createPurgeCommandData.dmPermission				= false;
			createPurgeCommandData.description				= "Purges a bulk of messages, possibly from a particular user.";
			createPurgeCommandData.name						= "purge";
			createPurgeCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createPurgeCommandData.type						= ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createPurgeOptionOne;
			createPurgeOptionOne.type		 = ApplicationCommandOptionType::Integer;
			createPurgeOptionOne.name		 = "amount";
			createPurgeOptionOne.minValue	 = 1;
			createPurgeOptionOne.maxValue	 = 10000;
			createPurgeOptionOne.required	 = true;
			createPurgeOptionOne.description = "The quantity of messages to delete.";
			createPurgeCommandData.options.emplace_back(createPurgeOptionOne);
			ApplicationCommandOptionData createPurgeOptionTwo;
			createPurgeOptionTwo.type		 = ApplicationCommandOptionType::UserData;
			createPurgeOptionTwo.name		 = "user";
			createPurgeOptionTwo.required	 = false;
			createPurgeOptionTwo.description = "An optional user, who's messages will be deleted.";
			createPurgeCommandData.options.emplace_back(createPurgeOptionTwo);
			ApplicationCommandOptionData createPurgeOptionThree;
			createPurgeOptionThree.type		   = ApplicationCommandOptionType::String;
			createPurgeOptionThree.name		   = "user_id";
			createPurgeOptionThree.required	   = false;
			createPurgeOptionThree.description = "An optional user, who's messages will be deleted.";
			createPurgeCommandData.options.emplace_back(createPurgeOptionThree);
			ApplicationCommandOptionData createPurgeOptionFour;
			createPurgeOptionFour.type		  = ApplicationCommandOptionType::Boolean;
			createPurgeOptionFour.name		  = "deletepinned";
			createPurgeOptionFour.required	  = false;
			createPurgeOptionFour.description = "Do we delete pinned messages?";
			createPurgeCommandData.options.emplace_back(createPurgeOptionFour);

			createServerInfoCommandData.dmPermission			 = false;
			createServerInfoCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createServerInfoCommandData.description				 = "Displays info about the current server.";
			createServerInfoCommandData.name					 = "serverinfo";
			createServerInfoCommandData.type					 = ApplicationCommandType::Chat_Input;

			createSetBorderColorCommandData.dmPermission			 = false;
			createSetBorderColorCommandData.description				 = "Set the default color of borders.";
			createSetBorderColorCommandData.name					 = "setbordercolor";
			createSetBorderColorCommandData.type					 = ApplicationCommandType::Chat_Input;
			createSetBorderColorCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			ApplicationCommandOptionData createSetBorderColoreOptionOne;
			createSetBorderColoreOptionOne.type		   = ApplicationCommandOptionType::String;
			createSetBorderColoreOptionOne.name		   = "botname";
			createSetBorderColoreOptionOne.description = "Which of the bots to change the setting on.";
			createSetBorderColoreOptionOne.required	   = true;
			ApplicationCommandOptionChoiceData setBorderColorchoiceOne;
			setBorderColorchoiceOne.name  = "janny";
			setBorderColorchoiceOne.value = "janny";
			createSetBorderColoreOptionOne.choices.emplace_back(setBorderColorchoiceOne);
			createSetBorderColorCommandData.options.emplace_back(createSetBorderColoreOptionOne);
			ApplicationCommandOptionData createSetBorderColorOptionTwo;
			createSetBorderColorOptionTwo.type		  = ApplicationCommandOptionType::String;
			createSetBorderColorOptionTwo.name		  = "hexcolorvalue";
			createSetBorderColorOptionTwo.required	  = true;
			createSetBorderColorOptionTwo.description = "The hex-color-value to set the borders to.";
			createSetBorderColorCommandData.options.emplace_back(createSetBorderColorOptionTwo);

			createUserInfoCommandData.dmPermission			   = false;
			createUserInfoCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createUserInfoCommandData.type					   = ApplicationCommandType::Chat_Input;
			createUserInfoCommandData.description			   = "Displays info about a chosen user.";
			createUserInfoCommandData.name					   = "userinfo";
			ApplicationCommandOptionData createUserInfoOptionOne;
			createUserInfoOptionOne.type		= ApplicationCommandOptionType::UserData;
			createUserInfoOptionOne.name		= "user";
			createUserInfoOptionOne.description = "Which of the users to view info about.";
			createUserInfoOptionOne.required	= true;
			createUserInfoCommandData.options.emplace_back(createUserInfoOptionOne);

			createSetInvitesChannelCommandData.dmPermission				= false;
			createSetInvitesChannelCommandData.description				= "Set the invite tracking channel and enables, or disables it.";
			createSetInvitesChannelCommandData.name						= "setinviteschannel";
			createSetInvitesChannelCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createSetInvitesChannelCommandData.type						= ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createSetInvitesChannelOptionOne;
			createSetInvitesChannelOptionOne.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetInvitesChannelOptionOne.name		 = "add";
			createSetInvitesChannelOptionOne.description = "Add the current channel as the invites-tracking channel, and activate it.";
			ApplicationCommandOptionData createSetInvitesChannelOptionOneOne;
			createSetInvitesChannelOptionOneOne.type		= ApplicationCommandOptionType::String;
			createSetInvitesChannelOptionOneOne.name		= "add";
			createSetInvitesChannelOptionOneOne.description = "Enable the invite-tracking.";
			createSetInvitesChannelOptionOneOne.required	= true;
			ApplicationCommandOptionChoiceData createSetInvitesChoiceOne;
			createSetInvitesChoiceOne.name	= "add";
			createSetInvitesChoiceOne.value = "add";
			createSetInvitesChannelOptionOneOne.choices.emplace_back(createSetInvitesChoiceOne);
			createSetInvitesChannelOptionOne.options.emplace_back(createSetInvitesChannelOptionOneOne);
			createSetInvitesChannelCommandData.options.emplace_back(createSetInvitesChannelOptionOne);
			ApplicationCommandOptionData createSetInvitesChannelOptionTwo;
			createSetInvitesChannelOptionTwo.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetInvitesChannelOptionTwo.name		 = "remove";
			createSetInvitesChannelOptionTwo.description = "remove the current channel as the invites-tracking channel, and deactivate it.";
			ApplicationCommandOptionData createSetInvitesChannelOptionTwoOne;
			createSetInvitesChannelOptionTwoOne.type		= ApplicationCommandOptionType::String;
			createSetInvitesChannelOptionTwoOne.name		= "remove";
			createSetInvitesChannelOptionTwoOne.description = "Cancel the invite tracking.";
			createSetInvitesChannelOptionTwoOne.required	= true;
			ApplicationCommandOptionChoiceData createSetInvitesChoiceTwo;
			createSetInvitesChoiceTwo.name	= "remove";
			createSetInvitesChoiceTwo.value = "remove";
			createSetInvitesChannelOptionTwoOne.choices.emplace_back(createSetInvitesChoiceTwo);
			createSetInvitesChannelOptionTwo.options.emplace_back(createSetInvitesChannelOptionTwoOne);
			createSetInvitesChannelCommandData.options.emplace_back(createSetInvitesChannelOptionTwo);
			ApplicationCommandOptionData createSetInvitesChannelOptionThree;
			createSetInvitesChannelOptionThree.type		   = ApplicationCommandOptionType::Sub_Command;
			createSetInvitesChannelOptionThree.name		   = "view";
			createSetInvitesChannelOptionThree.description = "Displays the current list of members and their respective invite-counts.";
			ApplicationCommandOptionData createSetInvitesChannelOptionThreeOne;
			createSetInvitesChannelOptionThreeOne.type		  = ApplicationCommandOptionType::String;
			createSetInvitesChannelOptionThreeOne.name		  = "view";
			createSetInvitesChannelOptionThreeOne.description = "Displays the current invite-counts.";
			createSetInvitesChannelOptionThreeOne.required	  = true;
			ApplicationCommandOptionChoiceData createSetInvitesChoiceThree;
			createSetInvitesChoiceThree.name  = "view";
			createSetInvitesChoiceThree.value = "view";
			createSetInvitesChannelOptionThreeOne.choices.emplace_back(createSetInvitesChoiceThree);
			createSetInvitesChannelOptionThree.options.emplace_back(createSetInvitesChannelOptionThreeOne);
			createSetInvitesChannelCommandData.options.emplace_back(createSetInvitesChannelOptionThree);

			createBanCommandData.dmPermission			  = false;
			createBanCommandData.description			  = "Ban a user or look at the banner's leaderboard.";
			createBanCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createBanCommandData.name					  = "ban";
			createBanCommandData.type					  = ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createBanOptionThree;
			createBanOptionThree.type		 = ApplicationCommandOptionType::Sub_Command;
			createBanOptionThree.name		 = "view";
			createBanOptionThree.description = "Displays the current leaderboard of banners.";
			createBanCommandData.options.emplace_back(createBanOptionThree);
			ApplicationCommandOptionData createBanOptionOne;
			createBanOptionOne.type		   = ApplicationCommandOptionType::Sub_Command;
			createBanOptionOne.name		   = "add";
			createBanOptionOne.description = "Adds a user to the banned list.";
			ApplicationCommandOptionData createBanOptionOneOne;
			createBanOptionOneOne.type		  = ApplicationCommandOptionType::UserData;
			createBanOptionOneOne.name		  = "user";
			createBanOptionOneOne.description = "The user to ban.";
			createBanOptionOneOne.required	  = true;
			createBanOptionOne.options.emplace_back(createBanOptionOneOne);
			ApplicationCommandOptionData createBanOptionOneTwo;
			createBanOptionOneTwo.type		  = ApplicationCommandOptionType::String;
			createBanOptionOneTwo.name		  = "reason";
			createBanOptionOneTwo.description = "The reason for the ban.";
			createBanOptionOneTwo.required	  = true;
			createBanOptionOne.options.emplace_back(createBanOptionOneTwo);
			ApplicationCommandOptionData createBanOptionOneThree;
			createBanOptionOneThree.type		= ApplicationCommandOptionType::Integer;
			createBanOptionOneThree.minValue	= 1;
			createBanOptionOneThree.maxValue	= 7;
			createBanOptionOneThree.name		= "numberofdaystopurge";
			createBanOptionOneThree.description = "The number of days of the user's messages to purge.";
			createBanOptionOneThree.required	= false;
			createBanOptionOne.options.emplace_back(createBanOptionOneThree);
			createBanCommandData.options.emplace_back(createBanOptionOne);

			createSetDeletionStatusCommandData.dmPermission				= false;
			createSetDeletionStatusCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createSetDeletionStatusCommandData.description				= "Enables or disables message-purging in a given channel.";
			createSetDeletionStatusCommandData.name						= "setdeletionstatus";
			createSetDeletionStatusCommandData.type						= ApplicationCommandType::Chat_Input;
			ApplicationCommandOptionData createSetDeletionStatusOptionOne;
			createSetDeletionStatusOptionOne.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetDeletionStatusOptionOne.name		 = "add";
			createSetDeletionStatusOptionOne.description = "Add the current channel as a message-purging channel.";
			ApplicationCommandOptionData createSetDeletionStatusOptionOneTwo;
			createSetDeletionStatusOptionOneTwo.type		= ApplicationCommandOptionType::Integer;
			createSetDeletionStatusOptionOneTwo.name		= "quantity";
			createSetDeletionStatusOptionOneTwo.minValue	= 1;
			createSetDeletionStatusOptionOneTwo.maxValue	= 100000;
			createSetDeletionStatusOptionOneTwo.description = "The number of messages to save in the channel.";
			createSetDeletionStatusOptionOneTwo.required	= true;
			createSetDeletionStatusOptionOne.options.emplace_back(createSetDeletionStatusOptionOneTwo);

			ApplicationCommandOptionData createSetDeletionStatusOptionOneThree;
			createSetDeletionStatusOptionOneThree.type		  = ApplicationCommandOptionType::Integer;
			createSetDeletionStatusOptionOneThree.minValue	  = 1;
			createSetDeletionStatusOptionOneThree.maxValue	  = 100000;
			createSetDeletionStatusOptionOneThree.name		  = "minutestosave";
			createSetDeletionStatusOptionOneThree.description = "The number of minutes to save the messages before deleting them.";
			createSetDeletionStatusOptionOneThree.required	  = true;
			createSetDeletionStatusOptionOne.options.emplace_back(createSetDeletionStatusOptionOneThree);
			createSetDeletionStatusCommandData.options.emplace_back(createSetDeletionStatusOptionOne);

			ApplicationCommandOptionData createSetDeletionStatusOptionTwo;
			createSetDeletionStatusOptionTwo.type		 = ApplicationCommandOptionType::Sub_Command;
			createSetDeletionStatusOptionTwo.name		 = "remove";
			createSetDeletionStatusOptionTwo.description = "remove the current channel as a message-purging channel.";

			createSetDeletionStatusCommandData.options.emplace_back(createSetDeletionStatusOptionTwo);
			ApplicationCommandOptionData createSetDeletionStatusOptionThree;
			createSetDeletionStatusOptionThree.type		   = ApplicationCommandOptionType::Sub_Command;
			createSetDeletionStatusOptionThree.name		   = "view";
			createSetDeletionStatusOptionThree.description = "Displays the current list of message-purging channels.";

			createSetDeletionStatusCommandData.options.emplace_back(createSetDeletionStatusOptionThree);

			createUserInfoData.dmPermission				= false;
			createUserInfoData.type						= ApplicationCommandType::UserData;
			createUserInfoData.name						= "UserData Info";
			createUserInfoData.defaultMemberPermissions = Permission::Use_Application_Commands;

			createApplicationCommandsCommandData.dmPermission			  = false;
			createApplicationCommandsCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createApplicationCommandsCommandData.type					  = ApplicationCommandType::Chat_Input;
			createApplicationCommandsCommandData.description			  = "Register the programmatically designated slash commands.";
			createApplicationCommandsCommandData.name					  = "registerapplicationcommands";

			createTestData.dmPermission				= true;
			createTestData.type						= ApplicationCommandType::Chat_Input;
			createTestData.name						= "test";
			createTestData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createTestData.description				= "Test command.";
			ApplicationCommandOptionData createTestCommandOptionOne{};
			createTestCommandOptionOne.type		   = ApplicationCommandOptionType::String;
			createTestCommandOptionOne.name		   = "test";
			createTestCommandOptionOne.required	   = true;
			createTestCommandOptionOne.description = "The test to be entered.";
			createTestData.options.emplace_back(createTestCommandOptionOne);

			createManageLogsData.dmPermission			  = false;
			createManageLogsData.type					  = ApplicationCommandType::Chat_Input;
			createManageLogsData.name					  = "managelogs";
			createManageLogsData.description			  = "Check the status and/or set the status of various logs.";
			createManageLogsData.defaultMemberPermissions = Permission::Use_Application_Commands;
			ApplicationCommandOptionData createManageLogsOptionOh;
			createManageLogsOptionOh.type		 = ApplicationCommandOptionType::Sub_Command;
			createManageLogsOptionOh.description = "View the currently enabled/disabled logs.";
			createManageLogsOptionOh.name		 = "view";
			createManageLogsData.options.emplace_back(createManageLogsOptionOh);
			ApplicationCommandOptionData createManageLogsOptionOne;
			createManageLogsOptionOne.type		  = ApplicationCommandOptionType::Sub_Command;
			createManageLogsOptionOne.description = "Group 1 of the potential logs to set.";
			createManageLogsOptionOne.name		  = "group1";
			ApplicationCommandOptionData createManageLogsOptionOhOne;
			createManageLogsOptionOhOne.name		= "settowhat";
			createManageLogsOptionOhOne.description = "Enable or disable the currently selected log?";
			createManageLogsOptionOhOne.required	= true;
			createManageLogsOptionOhOne.type		= ApplicationCommandOptionType::Boolean;
			createManageLogsOptionOne.options.emplace_back(createManageLogsOptionOhOne);
			ApplicationCommandOptionData createManageLogsOptionOneOne;
			createManageLogsOptionOneOne.name		 = "group1option";
			createManageLogsOptionOneOne.description = "Select which log you would like to set.";
			createManageLogsOptionOneOne.required	 = true;
			createManageLogsOptionOneOne.type		 = ApplicationCommandOptionType::String;

			DiscordGuild theGuild{};
			for (int32_t x = 0; x < 10; x += 1) {
				ApplicationCommandOptionChoiceData choiceDataOne;
				choiceDataOne.name	= theGuild.data.logs[x].name;
				choiceDataOne.value = jsonifier::string{ theGuild.data.logs[x].nameSmall };
				createManageLogsOptionOneOne.choices.emplace_back(choiceDataOne);
			}
			createManageLogsOptionOne.options.emplace_back(createManageLogsOptionOneOne);
			createManageLogsData.options.emplace_back(createManageLogsOptionOne);
			ApplicationCommandOptionData createManageLogsOptionTwo;
			createManageLogsOptionTwo.type		  = ApplicationCommandOptionType::Sub_Command;
			createManageLogsOptionTwo.description = "Group 2 of the potential logs to set.";
			createManageLogsOptionTwo.name		  = "group2";
			ApplicationCommandOptionData createManageLogsOptionOhTwo;
			createManageLogsOptionOhTwo.name		= "settowhat";
			createManageLogsOptionOhTwo.description = "Enable or disable the currently selected log?";
			createManageLogsOptionOhTwo.required	= true;
			createManageLogsOptionOhTwo.type		= ApplicationCommandOptionType::Boolean;
			createManageLogsOptionTwo.options.emplace_back(createManageLogsOptionOhTwo);
			ApplicationCommandOptionData createManageLogsOptionTwoOne;
			createManageLogsOptionTwoOne.name		 = "group2option";
			createManageLogsOptionTwoOne.description = "Select which log you would like to set.";
			createManageLogsOptionTwoOne.required	 = true;
			createManageLogsOptionTwoOne.type		 = ApplicationCommandOptionType::String;
			for (int32_t x = 10; x < theGuild.data.logs.size(); x += 1) {
				ApplicationCommandOptionChoiceData choiceDataOne;
				choiceDataOne.name	= theGuild.data.logs[x].name;
				choiceDataOne.value = jsonifier::string{ theGuild.data.logs[x].nameSmall };
				createManageLogsOptionTwoOne.choices.emplace_back(choiceDataOne);
			}
			createManageLogsOptionTwo.options.emplace_back(createManageLogsOptionTwoOne);
			createManageLogsData.options.emplace_back(createManageLogsOptionTwo);

			createHelpData.dmPermission				= true;
			createHelpData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createHelpData.type						= ApplicationCommandType::Chat_Input;
			createHelpData.name						= "help";
			createHelpData.description				= "A help command for this bot.";

			createAvatarData.dmPermission			  = false;
			createAvatarData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createAvatarData.type					  = ApplicationCommandType::Chat_Input;
			createAvatarData.description			  = "Displays the getUserImageUrl(UserImageTypes::Avatar) of a chosen user.";
			createAvatarData.name					  = "avatar";
			createAvatarData.defaultMemberPermissions = Permission::Use_Application_Commands;
			ApplicationCommandOptionData createAvatarOptionOne{};
			createAvatarOptionOne.type		  = ApplicationCommandOptionType::UserData;
			createAvatarOptionOne.name		  = "user";
			createAvatarOptionOne.description = "Which of the users to view the getUserImageUrl(UserImageTypes::Avatar) of.";
			createAvatarOptionOne.required	  = true;
			createAvatarData.options.emplace_back(createAvatarOptionOne);

			createPushmeCommandData.dmPermission			 = false;
			createPushmeCommandData.defaultMemberPermissions = Permission::Use_Application_Commands;
			createPushmeCommandData.name					 = "pushme";
			createPushmeCommandData.type					 = ApplicationCommandType::Chat_Input;
			createPushmeCommandData.description				 = "Push me to find out!";
		}
		CreateGlobalApplicationCommandData reactionRoleData{};
		CreateGlobalApplicationCommandData createStreamAudioData{};
		CreateGlobalApplicationCommandData createDisconnectData{};
		CreateGlobalApplicationCommandData createSetDefaultRoleIdsData{};
		CreateGlobalApplicationCommandData createBotInfoCommandData{};
		CreateGlobalApplicationCommandData createDisplayGuildsDataCommandData{};
		CreateGlobalApplicationCommandData createGhostCommandData{};
		CreateGlobalApplicationCommandData createPurgeCommandData{};
		CreateGlobalApplicationCommandData createServerInfoCommandData{};
		CreateGlobalApplicationCommandData createSetBorderColorCommandData{};
		CreateGlobalApplicationCommandData createUserInfoCommandData{};
		CreateGlobalApplicationCommandData createSetInvitesChannelCommandData{};
		CreateGlobalApplicationCommandData createBanCommandData{};
		CreateGlobalApplicationCommandData createSetDeletionStatusCommandData{};
		CreateGlobalApplicationCommandData createUserInfoData{};
		CreateGlobalApplicationCommandData createApplicationCommandsCommandData{};
		CreateGlobalApplicationCommandData createTestData{};
		CreateGlobalApplicationCommandData createManageLogsData{};
		CreateGlobalApplicationCommandData createHelpData{};
		CreateGlobalApplicationCommandData createAvatarData{};
		CreateGlobalApplicationCommandData createPushmeCommandData{};
	};


}// namespace DiscordCoreAPI
